### PR TITLE
moved local.conf and bblayers.conf out of the meta-sol repo into the …

### PR DESCRIPTION
**Pull request by Atomicchipmonk**
…manifest repo. Also removed tegra-sfm to allow for building

### CODE REVIEW

**Comment by Atomicchipmonk** [comment]
@alexhholmes I removed the sfm stuff for right now to allow us to build cleanly. Otherwise I just moved the bblayers.conf and local.conf to the other repo.

**Comment by alexhholmes** [comment]
@Atomicchipmonk What is the reason for moving the configuration files to a different repo?

**Comment by Atomicchipmonk** [comment]
Mainly because they felt weird being global configuration files in a meta package. I dont think I am hard set on them being in either place, the conf folder just felt a little polluted (both meta-sol stuff and global stuff).

You also talk about how to make those files in the README which i think is useful and the general way yocto is advertised. The repo-manifest repo basically has our entire global environment in it, so i thought the global conf files should live there too.

**Comment by alexhholmes** [comment]
Alternatively, would you be okay with me just making changes to the local.conf.template. It would have only layer specific configs that can be overwritten by an appended config that JHU can have in the manifest repo with. i.e. In local.conf.template in meta-sol `MACHINE ?=` rather than 'MACHINE ='.
This way we have a common layer specific template and both JHU and UGA can have our own CI repos that append changes to the common config file.

**Comment by Atomicchipmonk** [comment]
Sure! Yeah if you want to keep them in there, that works for me. I think this is a case where having it in two places doesn't hurt. Feel free to put them back in.

**Pull request closed without merging**
